apiVersion: v1
kind: Secret
metadata:
  labels:
    app: cvnd
    argocd.argoproj.io/secret-type: repository
  name: cvnd
  namespace: openshift-gitops
stringData:
  project: cvnd 
  type: git
  url: https://github.com/agbaroni/cloud-very-native-demo.git
