{{- range .Values.images }}
---
apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  annotations:
    build.shipwright.io/verify.repository: "true"
  name: {{ .name }}
  namespace: cvnd
spec:
  output:
    image: image-registry.openshift-image-registry.svc:5000/cvnd/{{ .name }}:latest
  paramValues:
    - name: dockerfile
      value: Containerfile
    - name: registries-search
      values:
        - value: image-registry.openshift-image-registry.svc:5000
        - value: registry.redhat.io
        - value: quay.io
  source:
    type: Git
    git:
      url: https://github.com/agbaroni/cloud-very-native-demo
    contextDir: images/{{ .name }}
  strategy:
    kind: ClusterBuildStrategy
    name: buildah
  {{- if gt (len .dependencies) 0 -}}
  triggers:
    when:
      {{- range .dependencies -}}
      - name: {{ . }}
        type: Image
        image:
          names:
            - image-registry.openshift-image-registry.svc:5000/cvnd/{{ . }}:latest
      {{- end -}}
  {{- end -}}
{{- end }}
