{{- range .Values.images }}
---
apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  annotations:
    build.shipwright.io/verify.repository: "true"
  name: {{ . }}
  namespace: cvnd
spec:
  output:
    image: image-registry.openshift-image-registry.svc:5000/cvnd/{{ . }}:latest
  paramValues:
    - name: dockerfile
      value: Containerfile
    - name: registries-search
      values:
        - image-registry.openshift-image-registry.svc:5000/cvnd
        - registry.redhat.io
        - quay.io
  source:
    type: Git
    git:
      url: https://github.com/agbaroni/cloud-very-native-demo
    contextDir: images/{{ . }}
  strategy:
    kind: ClusterBuildStrategy
    name: buildah
{{- end }}
