---
apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  annotations:
    build.shipwright.io/verify.repository: "true"
  name: common
  namespace: cvnd
spec:
  output:
    image: image-registry.openshift-image-registry.svc:5000/cvnd/common:latest
  paramValues:
    - name: build-args
      value:
        - value: BOOST_MAJOR=1
        - value: BOOST_MINOR=86
        - value: BOOST_MICRO=0
    - name: dockerfile
      value: Containerfile
  source:
    type: Git
    git:
      url: https://github.com/agbaroni/cloud-very-native-demo
    contextDir: images/common
  strategy:
    kind: ClusterBuildStrategy
    name: buildah
