{{- range .Values.images }}
apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  annotations:
    build.shipwright.io/verify.repository: "true"
  name: {{ . }}
  namespace: cvnd
spec:
  output:
    image: image-registry.openshift-image-registry.svc:5000/cvnd/{{ . }}:latest
  paramValues:
    - name: dockerfile
      value: Containerfile
    - name: registry-search
      value: image-registry.openshift-image-registry.svc:5000/cvnd
  source:
    type: Git
    git:
      url: https://github.com/agbaroni/cloud-very-native-demo
    contextDir: images/{{ . }}
  strategy:
    kind: ClusterBuildStrategy
    name: buildah
{{- end }}
