---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: cvnd
  name: common
  namespace: cvnd
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: cvnd
  name: compilation
  namespace: cvnd
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: cvnd
  name: execution
  namespace: cvnd
spec:
  lookupPolicy:
    local: true
