{{- range .Values.images }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: cvnd
  name: {{ .name }}
  namespace: cvnd
spec:
  lookupPolicy:
    local: true
{{- end }}
