apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: launch-builds
  namespace: cvnd
spec:
  tasks:
  {{- range .Values.images }}
    {{- if .pipeline }}
    - name: launch-build-{{ .name }}
      params:
        - name: build-name
          value: {{ .name }}
      taskRef:
        name: launch-build
      {{- if .dependencies }}
      runAfter:
        {{- range .dependencies }}
        - launch-build-{{ . }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
