apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: launch-build
  namespace: cvnd
spec:
  tasks:
    - name: launch-build-common
      params:
        - name: build-name
          value: common
      taskRef:
        name: launch-build
    - name: launch-build-compilation
      params:
        - name: build-name
          value: compilation
      taskRef:
        name: launch-build
    - name: launch-build-execution
      params:
        - name: build-name
          value: execution
      taskRef:
        name: launch-build
