---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: cvnd
subjects:
  - apiGroup: v1
    kind: ServiceAccount
    name: run-builds
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: run-builds
