---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: run-builds
  namespace: cvnd
rules:
  - apiGroups:
      - shipwright.io
    resources:
      - buildruns
    verbs:
      - '*'
