---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: launch-build
  namespace: cvnd
spec:
  params:
    - description: The name of a Build to run
      name: build-name
      type: string
  steps:
    - image: image-registry.openshift-image-registry.svc:5000/cvnd/openshift-client:latest
      name: oc-run
      script: |
        cat <<EOF | /usr/local/bin/oc apply -f -
        apiVersion: shipwright.io/v1beta1
        kind: BuildRun
        metadata:
          name: $(params.build-name)-$RANDOM-$RANDOM
          namespace: cvnd
        spec:
          build:
            name: $(params.build-name)
        EOF
    - image: image-registry.openshift-image-registry.svc:5000/cvnd/openshift-client:latest
      name: oc-check
      script: |
        while true; do
          R=$(oc get buildrun execution-1-1 -ojsonpath='{.status.conditions[0].reason}')
          if [ "$R" != "Running" ]; then
            echo "Unexpected status: $R"
            break
          fi
        done

