---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: launch-build
  namespace: cvnd
spec:
  params:
    - description: The name of a Build to run
      name: build-name
      type: string
  results:
    - description: The BuildRun's name
      name: buildrun-name
  steps:
    - image: image-registry.openshift-image-registry.svc:5000/cvnd/openshift-client:latest
      name: oc-run
      script: |
        NAME=$(params.build-name)-$RANDOM-$RANDOM
        echo $NAME > $(results.buildrun-name.path)
        cat <<EOF | /usr/local/bin/oc apply -f -
        apiVersion: shipwright.io/v1beta1
        kind: BuildRun
        metadata:
          name: $NAME
          namespace: cvnd
        spec:
          build:
            name: $(params.build-name)
        EOF
    - image: image-registry.openshift-image-registry.svc:5000/cvnd/openshift-client:latest
      name: oc-check
      script: |
        NAME=$(cat $(results.buildrun-name.path))
        while true; do
          R=$(oc get buildrun $NAME -ojsonpath='{.status.conditions[0].reason}')
          if [ -n "$R" ]; then
            if [ "$R" != "Running" ]; then
              if [ "$R" != "Succeeded" ]; then
                echo "Unexpected status: $R"
              fi
              break
            fi
          fi
        done
