images:
  - name: application_compilation
    dependencies:
      - compilation
  - name: application_execution
    dependencies: []
  - name: common
    dependencies: []
  - name: compilation
    dependencies:
      - common
  - name: execution
    depencencies:
      - common
  - name: openshift_client
    dependencies: []
