images:
  #- name: application-execution
  #  dependencies: []
  - name: common
    dependencies: []
    pipeline: true
  - name: compilation
    dependencies:
      - common
    pipeline: true
  - name: execution
    dependencies:
      - common
    pipeline: true
  - name: openshift-client
    dependencies: []
    pipeline: false
  - name: application-compilation
    dependencies:
      - compilation
    pipeline: true
