FROM cvnd/compilation:latest

RUN /bin/bash -c 'ls /workspace'

RUN /usr/bin/cmake -S /workspace/source/development -B _build -G Ninja \
 && /usr/bin/cmake --build _build \
 && /usr/bin/cmake --install _build
